[package]
name = "wallet"
version = "0.1.0"
authors = ["DFINITY Stiftung <sdk@dfinity.org>"]
edition = "2018"

[profile.release]
lto = true
opt-level = 'z'

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
candid = "0.6.17"
ic-types = "0.1.2"
ic-cdk = "0.2.3"
ic-cdk-macros = "0.2.3"
num-traits = "0.2.14"
serde = "1.0.116"
serde_bytes = "0.11"
